version: '3'
services:
    elasticsearchcrongo:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
      container_name: elasticsearch-cron-go
      ports: 
        - 9200:9200
        - 9300:9300
      environment:
        discovery.type: single-node
      networks:
        - cron_go_network
    
    kibanacrongo:
      image: docker.elastic.co/kibana/kibana:7.9.2
      container_name: kibana-cron-go
      depends_on:
        - elasticsearchcrongo
      ports:
        - 5601:5601
      environment:
        ELASTICSEARCH_URL: http://elasticsearchcrongo:9200
        ELASTICSEARCH_HOSTS: http://elasticsearchcrongo:9200
      networks:
        - cron_go_network
    filebeat:
      container_name: filebeat-cron-go
      build: "./.infra/logstash"
      command: filebeat -e -strict.perms=false -c filebeat.yml -d "publish"
      depends_on:
        - elasticsearchcrongo
      volumes:
          - ./.infra/logstash/filebeat.yml:/usr/share/filebeat/filebeat.yml
          - ./.logs:/usr/share/filebeat/datalogs
      networks:
          - cron_go_network

    postgrescron:
      container_name: postgres-cron
      image: "postgres:13"
      depends_on:
        - filebeat
      ports:
        - "5432:5432"
      volumes:
        - ./.infra/datas/postgrescron:/var/lib/postgresql/data
      networks:
        - cron_go_network
      environment:
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=admin2021
        - POSTGRES_DB=postgrescron

    postgresapi:
      container_name: postgres-api
      depends_on:
        - filebeat
      image: "postgres:13"
      ports:
        - "6432:5432"
      volumes:
        - ./.infra/datas/postgresapi:/var/lib/postgresql/data
      networks:
        - cron_go_network
      environment:
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=admin2021
        - POSTGRES_DB=postgresapi
  
networks:
    cron_go_network:
        driver: bridge