filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/datalogs/*.log
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

output.elasticsearch:
  hosts: ["http://elasticsearchcrongo:9200"]

processors:
  - decode_json_fields:
      fields: ['message', 'file_name', 'system']
      target: json