filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/datalogs/*.log
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

output.elasticsearch:
  hosts: ["http://elasticsearchcrongo:9200"]
  # index: "%{[fields.system]}-%{[agent.version]}-%{+yyyy.MM.dd}"
filebeat.config.modules.path: ${path.config}/modules.d/*.yml

setup.kibana.host: "http://kibanacrongo:5601"

processors:
  - add_docker_metadata: ~
  - decode_json_fields:
      fields: ['message', 'file_name', 'system']
      target: json